# Copyright (C) 2025 Malcom3D <malcom3d.gpl@gmail.com>
#
# This file is part of pbrAudio.
#
# pbrAudio is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# pbrAudio is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with pbrAudio.  If not, see <https://www.gnu.org/licenses/>.
# SPDX-License-Identifier: GPL-3.0-or-later

[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pbrAudioRender"
dynamic = ["version"]
description = "Physically based rendered 3D acoustic render"
authors = [
    {name = "Malcom3D", email = "malcom3d.gpl@gmail.com"},
]
readme = "README.md"
keywords = ["template", "modular", "extensible"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.11"
dependencies = [
    "dask", "scipy", "numba", "numpy <=2.3.5",
    "resampy", "soundfile", "trimesh", "blosc2"
]

[project.optional-dependencies]
dev = [
]

[project.urls]
Homepage = "https://pbraudio.org"
Repository = "https://github.com/Malcom3D/pbrAudioRender"

[tool.cibuildwheel]
manylinux-x86_64-image = "manylinux2014"

[tool.cibuildwheel.linux]
archs = ["x86_64"]

[tool.setuptools_scm]
version_scheme = "no-guess-dev"
local_scheme = "no-local-version"
write_to_template = '''
"""Version information."""
__version__ = "{version}"
'''
write_to = "__version.py"
